extends RigidBody3D

@export var move_force: float = 60.0
@export var mouse_sensitivity: float = 0.002
@export var pitch_limit: float = 1.4
@export var max_speed: float = 8.0

@onready var camera: Camera3D = $Camera3D

var yaw: float = 0.0
var pitch: float = 0.0

func _ready() -> void:
	Input.mouse_mode = Input.MOUSE_MODE_CAPTURED

func _unhandled_input(event: InputEvent) -> void:
	if event is InputEventMouseMotion and Input.mouse_mode == Input.MOUSE_MODE_CAPTURED:
		yaw -= event.relative.x * mouse_sensitivity
		pitch = clamp(pitch - event.relative.y * mouse_sensitivity, -pitch_limit, pitch_limit)
		camera.rotation = Vector3(pitch, yaw, 0.0)  # both on camera, body never rotates
	elif event is InputEventKey and event.pressed and event.keycode == KEY_ESCAPE:
		Input.mouse_mode = Input.MOUSE_MODE_VISIBLE if Input.mouse_mode == Input.MOUSE_MODE_CAPTURED else Input.MOUSE_MODE_CAPTURED

func _physics_process(_delta: float) -> void:
	var dir := Vector3.ZERO
	if Input.is_key_pressed(KEY_W): dir -= camera.global_transform.basis.z
	if Input.is_key_pressed(KEY_S): dir += camera.global_transform.basis.z
	if Input.is_key_pressed(KEY_A): dir -= camera.global_transform.basis.x
	if Input.is_key_pressed(KEY_D): dir += camera.global_transform.basis.x
	if Input.is_key_pressed(KEY_SPACE): dir += Vector3.UP
	if Input.is_key_pressed(KEY_CTRL): dir -= Vector3.UP

	if dir.length_squared() > 0.0:
		dir = dir.normalized()
		# Don't push past max_speed
		if linear_velocity.dot(dir) < max_speed:
			apply_central_force(dir * move_force)

# generated by claude
